"""Add OtroEquipo table and link Mantenimiento

Revision ID: 995e8ede0130
Revises: c406702670ee
Create Date: 2025-04-16 21:41:55.809942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995e8ede0130'
down_revision: Union[str, None] = 'c406702670ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otros_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo del equipo'),
    sa.Column('tipo', sa.String(length=50), nullable=False, comment='Tipo de equipo (Motogenerador, UPS, PDU, etc.)'),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('codigo_inventario', sa.String(length=100), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('estado_operativo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True, comment='Información adicional relevante'),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_inventario'),
    sa.UniqueConstraint('serial')
    )
    op.add_column('mantenimientos', sa.Column('otro_equipo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mantenimientos', 'otros_equipos', ['otro_equipo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mantenimientos', type_='foreignkey')
    op.drop_column('mantenimientos', 'otro_equipo_id')
    op.drop_table('otros_equipos')
    # ### end Alembic commands ###
