"""Initial migration

Revision ID: c406702670ee
Revises: 
Create Date: 2025-04-11 19:25:21.748636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c406702670ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aires_acondicionados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True, comment='Ubicación general del equipo completo'),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True, comment='Tipo de aire (precision, confort, etc.)'),
    sa.Column('toneladas', sa.Float(), nullable=True, comment='Capacidad en toneladas de refrigeración'),
    sa.Column('evaporadora_operativa', sa.Boolean(), nullable=False, comment='Estado operativo de la evaporadora'),
    sa.Column('evaporadora_marca', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_modelo', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_serial', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_codigo_inventario', sa.String(length=100), nullable=True),
    sa.Column('evaporadora_ubicacion_instalacion', sa.String(length=200), nullable=True, comment='Ubicación específica de la evaporadora si difiere de la general'),
    sa.Column('condensadora_operativa', sa.Boolean(), nullable=False, comment='Estado operativo de la condensadora'),
    sa.Column('condensadora_marca', sa.String(length=100), nullable=True),
    sa.Column('condensadora_modelo', sa.String(length=100), nullable=True),
    sa.Column('condensadora_serial', sa.String(length=100), nullable=True),
    sa.Column('condensadora_codigo_inventario', sa.String(length=100), nullable=True),
    sa.Column('condensadora_ubicacion_instalacion', sa.String(length=200), nullable=True, comment='Ubicación específica de la condensadora si difiere de la general'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condensadora_codigo_inventario'),
    sa.UniqueConstraint('condensadora_serial'),
    sa.UniqueConstraint('evaporadora_codigo_inventario'),
    sa.UniqueConstraint('evaporadora_serial')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lecturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tecnico', sa.String(length=100), nullable=True),
    sa.Column('imagen_nombre', sa.String(length=255), nullable=True),
    sa.Column('imagen_tipo', sa.String(length=50), nullable=True),
    sa.Column('imagen_datos', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umbrales_configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aire_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('es_global', sa.Boolean(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('hum_min', sa.Float(), nullable=False),
    sa.Column('hum_max', sa.Float(), nullable=False),
    sa.Column('notificar_activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultima_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aire_id'], ['aires_acondicionados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('umbrales_configuracion')
    op.drop_table('mantenimientos')
    op.drop_table('lecturas')
    op.drop_table('usuarios')
    op.drop_table('aires_acondicionados')
    # ### end Alembic commands ###
