"""primer commit

Revision ID: cb0a7519e904
Revises: 35b554411640
Create Date: 2025-04-17 12:06:48.714498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0a7519e904'
down_revision: Union[str, None] = '35b554411640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mantenimientos_creado_por_id_fkey', 'mantenimientos', type_='foreignkey')
    op.drop_column('mantenimientos', 'creado_por_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mantenimientos', sa.Column('creado_por_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mantenimientos_creado_por_id_fkey', 'mantenimientos', 'usuarios', ['creado_por_id'], ['id'])
    # ### end Alembic commands ###
